services:
  - type: web
    name: quanter
    runtime: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: npm run preview
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
